#install dependencies - VTK, PCL, EIGEN, FLANN, Qt, libLAS
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libvtk6-dev
      - libeigen3-dev
      - cmake
      - libflann-dev
      - qt5-default
      - liblas-dev
      - liblas-bin
      - liblas3
      - libboost-all-dev
      - tar 
      - gzip 
      - zip 
      - unzip 
      - bzip2
  
# Enable C++ support
language: cpp

# Plaform
os: linux
#distribution
dist: xenial
# Compiler selection
compiler:
  - gcc
  
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  
  # install pcl from source
  - mkdir pcl && mkdir pcl_build && wget "https://codeload.github.com/janekT/pcl/zip/pointpicking" -O pcl.zip && unzip pcl.zip -d pcl
  - cd pcl_build && cmake ${TRAVIS_BUILD_DIR}/deps/pcl/pointpicking && make && make install
  
  
  # Go to the Root directory  
  - cd ..

# Build steps
script:
  - mkdir build
  - cd build
  - ${DEPS_DIR}/cmake/bin/cmake .. && make
