# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'macOS-latest'
steps:
- script: 
    echo instalation of dependencies
    
    brew install vtk boost eigen flann qt liblas cmake
    
    mkdir deps && cd deps  
    
    mkdir pcl && mkdir pcl_build
    
    wget "https://codeload.github.com/janekT/pcl/zip/pointpicking" -O pcl.zip
    
    unzip pcl.zip -d pcl
    
    cd pcl_build
    
    echo CMAKE
    
    cmake -S../pcl/pcl-pointpicking -DEIGEN_INCLUDE_DIR="/usr/include/eigen3/Eigen" -DFLANN_INCLUDE_DIR="/usr/include/flann" -DFLANN_LIBRARY="/usr/lib/x86_64-linux-gnu/libflann_cpp.so" -DVTK_DIR="/usr/local/lib/cmake/vtk-8.2"
    
    make -j$(($(nproc) - 1))
    make install
    cd ..
    cd ..

  displayName: 'Instalation of dependencies'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
