# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: 
    echo intalation of dependencies
    sudo apt-get update 
    
    sudo apt-get install -y --fix-missing qt5-default libvtk7-dev vtk7 libvtk7-qt-dev libeigen3-dev libeigen3-doc cmake libflann-dev liblas-dev liblas-bin liblas3
    
    sudo apt-get install -y --fix-missing libboost-all-dev
    
    mkdir deps && cd deps
    
    mkdir pcl && mkdir pcl_build
    
    echo WGET
    
    wget "https://codeload.github.com/janekT/pcl/zip/pointpicking" -O pcl.zip
    
    unzip pcl.zip -d pcl
    
    cd pcl_build
    
    echo CMAKE
    
    cmake -S../pcl/pcl-pointpicking -DEIGEN_INCLUDE_DIR="/usr/include/eigen3/Eigen" -DFLANN_INCLUDE_DIR="/usr/include/flann" -DFLANN_LIBRARY="/usr/lib/x86_64-linux-gnu/libflann_cpp.so" -DVTK_DIR="/usr/bin/vtk7"
    
    make 
    
    sudo make install
  
  
  # Go to the Root directory  
 # - cd ..
  #- cd ..

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
