# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: 
    echo intalation of dependencies
    sudo apt-get update && sudo apt-get install -y --fix-missing libvtk6-dev libeigen3-dev_3.3 cmake libflann-dev qt5-default liblas-dev liblas-bin liblas3 libboost-all-dev
    
    mkdir deps && cd deps
    
    mkdir pcl && mkdir pcl_build
    
    echo WGET
    
    wget "https://codeload.github.com/janekT/pcl/zip/pointpicking" -O pcl.zip
    
    unzip pcl.zip -d pcl
    
    cd pcl_build
    
    echo CMAKE
    
    cmake ../pcl/pcl-pointpicking
    
    make 
    
    sudo make install
  
  
  # Go to the Root directory  
 # - cd ..
  #- cd ..

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
